language: node_js
sudo: required
node_js:
  - "stable"
branches:
  only:
    - master
    before_script:
    - npm install firebase-tools -g
script:
  - echo "Deploying!"
deploy:
  skip_cleanup: true
  provider: firebase
  token: 
    secure: 
  project: "questions-veselov"
  after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
  